import { PERMISSIONS } from './permissions';
import { ROLES } from './roles';

export const ROLE_PERMISSIONS = {

  [ROLES.ADMIN]: Object.values(PERMISSIONS),

  [ROLES.USER]: [
    PERMISSIONS.USER_READ,
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.ORDER_READ,
    PERMISSIONS.REVIEW_CREATE,
    PERMISSIONS.REVIEW_READ,
  ],

  [ROLES.SELLER]: [
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_UPDATE,
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.ORDER_READ,
    PERMISSIONS.REVIEW_READ,
  ],

  [ROLES.GUEST]: [
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.REVIEW_READ,
  ],

};